CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE IF NOT EXISTS departments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL UNIQUE
);

ALTER TABLE departments
ALTER COLUMN id SET DEFAULT gen_random_uuid();

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'departments_title_key'
  ) THEN
    ALTER TABLE departments
    ADD CONSTRAINT departments_title_key UNIQUE (title);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS roles (
  id INT PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE,
  description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS accounts (
  user_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username CITEXT NOT NULL UNIQUE,
  disabled BOOLEAN NOT NULL DEFAULT FALSE,
  password_hash TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  user_id UUID PRIMARY KEY REFERENCES accounts(user_id) ON DELETE CASCADE,
  first_name TEXT NOT NULL DEFAULT '',
  last_name TEXT NOT NULL DEFAULT '',
  department UUID REFERENCES departments(id) ON DELETE SET NULL,
  email TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  logo TEXT NOT NULL DEFAULT '',
  latest_ticket UUID DEFAULT NULL
);

ALTER TABLE users
ADD COLUMN IF NOT EXISTS first_name TEXT NOT NULL DEFAULT '';

ALTER TABLE users
ADD COLUMN IF NOT EXISTS last_name TEXT NOT NULL DEFAULT '';

ALTER TABLE users
ADD COLUMN IF NOT EXISTS department UUID REFERENCES departments(id) ON DELETE SET NULL;

ALTER TABLE users
DROP COLUMN IF EXISTS department_id;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS email TEXT NOT NULL DEFAULT '';

ALTER TABLE users
ADD COLUMN IF NOT EXISTS phone TEXT NOT NULL DEFAULT '';

ALTER TABLE users
ADD COLUMN IF NOT EXISTS logo TEXT NOT NULL DEFAULT '';

ALTER TABLE users
ADD COLUMN IF NOT EXISTS latest_ticket UUID DEFAULT NULL;

CREATE TABLE IF NOT EXISTS account_roles (
  user_id UUID PRIMARY KEY REFERENCES accounts(user_id) ON DELETE CASCADE,
  role_id INT NOT NULL REFERENCES roles(id)
);
