CREATE TABLE IF NOT EXISTS clients (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  region UUID REFERENCES regions(id) ON DELETE SET NULL,
  address TEXT,
  location JSONB DEFAULT NULL,
  laboratory_system UUID DEFAULT NULL,
  manager UUID[] NOT NULL DEFAULT '{}'
);

ALTER TABLE clients
ALTER COLUMN id SET DEFAULT gen_random_uuid();

ALTER TABLE clients
ADD COLUMN IF NOT EXISTS title TEXT NOT NULL DEFAULT '';

ALTER TABLE clients
ADD COLUMN IF NOT EXISTS region UUID REFERENCES regions(id) ON DELETE SET NULL;

ALTER TABLE clients
ADD COLUMN IF NOT EXISTS address TEXT;

ALTER TABLE clients
ADD COLUMN IF NOT EXISTS location JSONB DEFAULT NULL;

ALTER TABLE clients
ADD COLUMN IF NOT EXISTS laboratory_system UUID DEFAULT NULL;

ALTER TABLE clients
ADD COLUMN IF NOT EXISTS manager UUID[] NOT NULL DEFAULT '{}';
