CREATE TABLE IF NOT EXISTS contacts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL DEFAULT '',
  position TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL DEFAULT '',
  client_id UUID REFERENCES clients(id) ON DELETE CASCADE
);

ALTER TABLE contacts
ALTER COLUMN id SET DEFAULT gen_random_uuid();

ALTER TABLE contacts
ADD COLUMN IF NOT EXISTS name TEXT NOT NULL DEFAULT '';

ALTER TABLE contacts
ADD COLUMN IF NOT EXISTS position TEXT NOT NULL DEFAULT '';

ALTER TABLE contacts
ADD COLUMN IF NOT EXISTS phone TEXT NOT NULL DEFAULT '';

ALTER TABLE contacts
ADD COLUMN IF NOT EXISTS email TEXT NOT NULL DEFAULT '';

ALTER TABLE contacts
ADD COLUMN IF NOT EXISTS client_id UUID REFERENCES clients(id) ON DELETE CASCADE;
