CREATE TABLE IF NOT EXISTS devices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  classificator UUID REFERENCES classificators(id) ON DELETE SET NULL,
  serial_number TEXT NOT NULL DEFAULT '',
  properties JSONB NOT NULL DEFAULT '{}',
  connected_to_lis BOOLEAN NOT NULL DEFAULT FALSE,
  is_used BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE devices
ALTER COLUMN id SET DEFAULT gen_random_uuid();

ALTER TABLE devices
ADD COLUMN IF NOT EXISTS classificator UUID REFERENCES classificators(id) ON DELETE SET NULL;

ALTER TABLE devices
ADD COLUMN IF NOT EXISTS serial_number TEXT NOT NULL DEFAULT '';

ALTER TABLE devices
ADD COLUMN IF NOT EXISTS properties JSONB NOT NULL DEFAULT '{}';

ALTER TABLE devices
ADD COLUMN IF NOT EXISTS connected_to_lis BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE devices
ADD COLUMN IF NOT EXISTS is_used BOOLEAN NOT NULL DEFAULT FALSE;
