CREATE TABLE IF NOT EXISTS ticket_statuses (
  type VARCHAR(128) PRIMARY KEY,
  title TEXT NOT NULL DEFAULT ''
);

ALTER TABLE ticket_statuses
ADD COLUMN IF NOT EXISTS title TEXT NOT NULL DEFAULT '';
