CREATE TABLE IF NOT EXISTS ticket_reasons (
  id VARCHAR(128) PRIMARY KEY,
  title TEXT NOT NULL DEFAULT '',
  past TEXT NOT NULL DEFAULT '',
  present TEXT NOT NULL DEFAULT '',
  future TEXT NOT NULL DEFAULT ''
);

ALTER TABLE ticket_reasons
ADD COLUMN IF NOT EXISTS title TEXT NOT NULL DEFAULT '';

ALTER TABLE ticket_reasons
ADD COLUMN IF NOT EXISTS past TEXT NOT NULL DEFAULT '';

ALTER TABLE ticket_reasons
ADD COLUMN IF NOT EXISTS present TEXT NOT NULL DEFAULT '';

ALTER TABLE ticket_reasons
ADD COLUMN IF NOT EXISTS future TEXT NOT NULL DEFAULT '';
