CREATE TABLE IF NOT EXISTS tickets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  number INT GENERATED ALWAYS AS IDENTITY,
  created_at TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
  assigned_at TIMESTAMP DEFAULT NULL,
  workstarted_at TIMESTAMP DEFAULT NULL,
  workfinished_at TIMESTAMP DEFAULT NULL,
  planned_start TIMESTAMP DEFAULT NULL,
  planned_end TIMESTAMP DEFAULT NULL,
  assigned_start TIMESTAMP DEFAULT NULL,
  assigned_end TIMESTAMP DEFAULT NULL,
  urgent BOOLEAN NOT NULL DEFAULT FALSE,
  closed_at TIMESTAMP DEFAULT NULL,
  client UUID REFERENCES clients(id) ON DELETE SET NULL,
  device UUID REFERENCES devices(id) ON DELETE SET NULL,
  ticket_type VARCHAR(128) REFERENCES ticket_types(type) ON DELETE SET NULL,
  author UUID REFERENCES accounts(user_id) ON DELETE SET NULL,
  department UUID REFERENCES departments(id) ON DELETE SET NULL,
  assigned_by UUID REFERENCES accounts(user_id) ON DELETE SET NULL DEFAULT NULL,
  reason VARCHAR(128) REFERENCES ticket_reasons(id) ON DELETE SET NULL,
  description TEXT NOT NULL DEFAULT '',
  contact_person UUID REFERENCES contacts(id) ON DELETE SET NULL,
  executor UUID REFERENCES accounts(user_id) ON DELETE SET NULL,
  status VARCHAR(128) REFERENCES ticket_statuses(type) ON DELETE SET NULL,
  result TEXT NOT NULL DEFAULT '',
  used_materials UUID[] NOT NULL DEFAULT '{}',
  reference_ticket UUID REFERENCES tickets(id) DEFAULT NULL,
  double_signed BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE tickets
ADD COLUMN IF NOT EXISTS number INT GENERATED ALWAYS AS IDENTITY;

ALTER TABLE tickets
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC');

ALTER TABLE tickets
ADD COLUMN IF NOT EXISTS assigned_at TIMESTAMP DEFAULT NULL;

ALTER TABLE tickets
ADD COLUMN IF NOT EXISTS workstarted_at TIMESTAMP DEFAULT NULL;

ALTER TABLE tickets
ADD COLUMN IF NOT EXISTS workfinished_at TIMESTAMP DEFAULT NULL;

ALTER TABLE tickets
ADD COLUMN IF NOT EXISTS planned_start TIMESTAMP DEFAULT NULL;

ALTER TABLE tickets
ADD COLUMN IF NOT EXISTS planned_end TIMESTAMP DEFAULT NULL;

ALTER TABLE tickets
ADD COLUMN IF NOT EXISTS assigned_start TIMESTAMP DEFAULT NULL;

ALTER TABLE tickets
ADD COLUMN IF NOT EXISTS assigned_end TIMESTAMP DEFAULT NULL;

ALTER TABLE tickets
ADD COLUMN IF NOT EXISTS urgent BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE tickets
ADD COLUMN IF NOT EXISTS closed_at TIMESTAMP DEFAULT NULL;

ALTER TABLE tickets
ADD COLUMN IF NOT EXISTS client UUID REFERENCES clients(id) ON DELETE SET NULL;

ALTER TABLE tickets
ADD COLUMN IF NOT EXISTS device UUID REFERENCES devices(id) ON DELETE SET NULL;

ALTER TABLE tickets
ADD COLUMN IF NOT EXISTS ticket_type VARCHAR(128) REFERENCES ticket_types(type) ON DELETE SET NULL;

ALTER TABLE tickets
ADD COLUMN IF NOT EXISTS author UUID REFERENCES accounts(user_id) ON DELETE SET NULL;

ALTER TABLE tickets
ADD COLUMN IF NOT EXISTS department UUID REFERENCES departments(id) ON DELETE SET NULL;

ALTER TABLE tickets
ADD COLUMN IF NOT EXISTS assigned_by UUID REFERENCES accounts(user_id) ON DELETE SET NULL DEFAULT NULL;

ALTER TABLE tickets
ADD COLUMN IF NOT EXISTS reason VARCHAR(128) REFERENCES ticket_reasons(id) ON DELETE SET NULL;

ALTER TABLE tickets
ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '';

ALTER TABLE tickets
ADD COLUMN IF NOT EXISTS contact_person UUID REFERENCES contacts(id) ON DELETE SET NULL;

ALTER TABLE tickets
ADD COLUMN IF NOT EXISTS executor UUID REFERENCES accounts(user_id) ON DELETE SET NULL;

ALTER TABLE tickets
ADD COLUMN IF NOT EXISTS status VARCHAR(128) REFERENCES ticket_statuses(type) ON DELETE SET NULL;

ALTER TABLE tickets
ADD COLUMN IF NOT EXISTS result TEXT NOT NULL DEFAULT '';

ALTER TABLE tickets
ADD COLUMN IF NOT EXISTS used_materials UUID[] NOT NULL DEFAULT '{}';

ALTER TABLE tickets
ADD COLUMN IF NOT EXISTS reference_ticket UUID REFERENCES tickets(id) DEFAULT NULL;

ALTER TABLE tickets
ADD COLUMN IF NOT EXISTS double_signed BOOLEAN NOT NULL DEFAULT FALSE;
