CREATE TABLE IF NOT EXISTS attachments (
  id TEXT NOT NULL PRIMARY KEY,
  name TEXT NOT NULL,
  media_type TEXT NOT NULL,
  ext TEXT NOT NULL,
  ref_id UUID NOT NULL
);

ALTER TABLE attachments
ADD COLUMN IF NOT EXISTS name TEXT NOT NULL DEFAULT '';

ALTER TABLE attachments
ADD COLUMN IF NOT EXISTS media_type TEXT NOT NULL DEFAULT '';

ALTER TABLE attachments
ADD COLUMN IF NOT EXISTS ext TEXT NOT NULL DEFAULT '';

ALTER TABLE attachments
ADD COLUMN IF NOT EXISTS ref_id UUID;

ALTER TABLE attachments
ADD COLUMN IF NOT EXISTS object_key TEXT NOT NULL DEFAULT '';

ALTER TABLE attachments
ADD COLUMN IF NOT EXISTS size_bytes BIGINT NOT NULL DEFAULT 0;

ALTER TABLE attachments
ADD COLUMN IF NOT EXISTS uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
