CREATE TABLE IF NOT EXISTS agreements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  number INT GENERATED ALWAYS AS IDENTITY,
  actual_client UUID REFERENCES clients(id) ON DELETE SET NULL,
  distributor UUID REFERENCES clients(id) ON DELETE SET NULL,
  device UUID REFERENCES devices(id) ON DELETE SET NULL,
  assigned_at TIMESTAMP DEFAULT NULL,
  finished_at TIMESTAMP DEFAULT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  on_warranty BOOLEAN NOT NULL DEFAULT TRUE,
  type VARCHAR(128)
);

ALTER TABLE agreements
ADD COLUMN IF NOT EXISTS number INT GENERATED ALWAYS AS IDENTITY;

ALTER TABLE agreements
ADD COLUMN IF NOT EXISTS actual_client UUID REFERENCES clients(id) ON DELETE SET NULL;

ALTER TABLE agreements
ADD COLUMN IF NOT EXISTS distributor UUID REFERENCES clients(id) ON DELETE SET NULL;

ALTER TABLE agreements
ADD COLUMN IF NOT EXISTS device UUID REFERENCES devices(id) ON DELETE SET NULL;

ALTER TABLE agreements
ADD COLUMN IF NOT EXISTS assigned_at TIMESTAMP DEFAULT NULL;

ALTER TABLE agreements
ADD COLUMN IF NOT EXISTS finished_at TIMESTAMP DEFAULT NULL;

ALTER TABLE agreements
ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE agreements
ADD COLUMN IF NOT EXISTS on_warranty BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE agreements
ADD COLUMN IF NOT EXISTS type VARCHAR(128);
