CREATE TABLE IF NOT EXISTS comments (
  id SERIAL PRIMARY KEY,
  author_id UUID NOT NULL REFERENCES accounts(user_id) ON DELETE CASCADE,
  reference_id UUID NOT NULL,
  text TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE comments
ADD COLUMN IF NOT EXISTS author_id UUID REFERENCES accounts(user_id) ON DELETE CASCADE;

ALTER TABLE comments
ADD COLUMN IF NOT EXISTS reference_id UUID;

ALTER TABLE comments
ADD COLUMN IF NOT EXISTS text TEXT NOT NULL DEFAULT '';

ALTER TABLE comments
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW();
