CREATE TABLE IF NOT EXISTS pouchdb_checkpoints (
  source TEXT PRIMARY KEY,
  last_seq TEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE TABLE IF NOT EXISTS pouchdb_documents (
  id TEXT PRIMARY KEY,
  rev TEXT NOT NULL DEFAULT '',
  deleted BOOLEAN NOT NULL DEFAULT FALSE,
  doc JSONB DEFAULT NULL,
  last_seq TEXT NOT NULL DEFAULT '',
  updated_at TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

ALTER TABLE pouchdb_checkpoints
ADD COLUMN IF NOT EXISTS last_seq TEXT NOT NULL DEFAULT '';

ALTER TABLE pouchdb_checkpoints
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC');

ALTER TABLE pouchdb_documents
ADD COLUMN IF NOT EXISTS rev TEXT NOT NULL DEFAULT '';

ALTER TABLE pouchdb_documents
ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE pouchdb_documents
ADD COLUMN IF NOT EXISTS doc JSONB DEFAULT NULL;

ALTER TABLE pouchdb_documents
ADD COLUMN IF NOT EXISTS last_seq TEXT NOT NULL DEFAULT '';

ALTER TABLE pouchdb_documents
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC');
