// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package db

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (username, password_hash)
VALUES ($1, $2)
RETURNING user_id, username, disabled, password_hash
`

type CreateAccountParams struct {
	Username     string
	PasswordHash string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Username, arg.PasswordHash)
	var i Account
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Disabled,
		&i.PasswordHash,
	)
	return i, err
}
