// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING token_id, user_id, token_hash, expires_at, created_at, rotated_at, replaced_by, revoked_at
`

type CreateRefreshTokenParams struct {
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.TokenID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.ReplacedBy,
		&i.RevokedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT token_id, user_id, token_hash, expires_at, created_at, rotated_at, replaced_by, revoked_at
FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.TokenID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.ReplacedBy,
		&i.RevokedAt,
	)
	return i, err
}

const rotateRefreshToken = `-- name: RotateRefreshToken :execrows
UPDATE refresh_tokens
SET rotated_at = NOW(), replaced_by = $2
WHERE token_id = $1
  AND rotated_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > NOW()
`

type RotateRefreshTokenParams struct {
	TokenID    pgtype.UUID
	ReplacedBy pgtype.UUID
}

func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateRefreshToken, arg.TokenID, arg.ReplacedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
