// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	UserID       pgtype.UUID
	Username     string
	Disabled     bool
	PasswordHash string
}

type AccountRole struct {
	UserID pgtype.UUID
	RoleID int32
}

type Department struct {
	ID    pgtype.UUID
	Title string
}

type Role struct {
	ID          int32
	Name        string
	Description pgtype.Text
}

type User struct {
	UserID       pgtype.UUID
	FirstName    string
	LastName     string
	DepartmentID pgtype.UUID
	Email        string
	Phone        string
	Logo         string
	LatestTicket pgtype.UUID
}
